### ISSUE TITLE
Handle configuration file errors

### ISSUE THREAD

**Issue by scottbarnesg** [scottbarnesg/WeatherByLocation#25]
```
[00:46:02] [Server thread/ERROR]: Cannot load plugins/WeatherByLocation/config.yml
org.bukkit.configuration.InvalidConfigurationException: expected '<document start>', but found '<block mapping start>'
 in 'reader', line 25, column 1:
    minutes-between-updates: 10
    ^

	at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:106) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:160) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:128) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.configuration.file.YamlConfiguration.loadConfiguration(YamlConfiguration.java:306) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.reloadConfig(JavaPlugin.java:172) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
	at mc.spigot.weatherbylocation.WeatherByLocation.runStartupTasks(WeatherByLocation.java:94) ~[WeatherByLocation-0.2.6.jar:?]
	at mc.spigot.weatherbylocation.WeatherByLocation.onEnable(WeatherByLocation.java:67) ~[WeatherByLocation-0.2.6.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:279) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189) ~[paper-1.19.4.jar:git-Paper-526]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[paper-1.19.4.jar:git-Paper-526]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_19_R3.CraftServer.enablePlugin(CraftServer.java:555) ~[paper-1.19.4.jar:git-Paper-526]
	at org.bukkit.craftbukkit.v1_19_R3.CraftServer.enablePlugins(CraftServer.java:466) ~[paper-1.19.4.jar:git-Paper-526]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:638) ~[paper-1.19.4.jar:git-Paper-526]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:437) ~[paper-1.19.4.jar:git-Paper-526]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:308) ~[paper-1.19.4.jar:git-Paper-526]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1104) ~[paper-1.19.4.jar:git-Paper-526]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[paper-1.19.4.jar:git-Paper-526]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: org.yaml.snakeyaml.parser.ParserException: expected '<document start>', but found '<block mapping start>'
 in 'reader', line 25, column 1:
    minutes-between-updates: 10
    ^

	at org.yaml.snakeyaml.parser.ParserImpl$ParseDocumentStart.produce(ParserImpl.java:274) ~[snakeyaml-1.33.jar:?]
	at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:185) ~[snakeyaml-1.33.jar:?]
	at org.yaml.snakeyaml.parser.ParserImpl.checkEvent(ParserImpl.java:175) ~[snakeyaml-1.33.jar:?]
	at org.yaml.snakeyaml.composer.Composer.getSingleNode(Composer.java:163) ~[snakeyaml-1.33.jar:?]
	at org.yaml.snakeyaml.Yaml.compose(Yaml.java:559) ~[snakeyaml-1.33.jar:?]
	at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:104) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
	... 18 more
```

**Comment by adrienzag** [comment]
How would you like the error(s) to be handled at this point, currently I wait and then shut down the Bukkit Server with the Bukkit.shutdown() method, but the way that it is done is not the prettiest

**Comment by scottbarnesg** [comment]
HI @adrien2-public, this is a challenging task that I haven't fully thought through. From what I understand, the Bukkit library catches config errors internally, which would mean this change may require implementing a completely separate. Definitely open to ideas if you have them.

**Comment by adrienzag** [comment]
Hi,

That is accurate, I wrote a little bit on this on my (now closed - because i had unrelated changes in other files) PR. I will create a new PR and you can let me know what you think.

The main issues are below:
- separate implementation is needed (as far as i found) to handle the config errors
- it is likely that in the future it may make sense to create a class that  will handle the config errors instead of what i currently have (which is the code in the WeatherByLocation.java class)
- I was not too sure about which config errors need their own logic, for example there are parse errors, IO errors, syntax etc
